### ISSUE TITLE
AWS synced_folder

### ISSUE THREAD

**Issue by aaronjudd** [mitchellh/vagrant-aws#105]
Question,I can't seem to get the AWS provider to sync (or ignore) any folder except the vagrant root.

No matter what the options I have tried it always says:
[solraws] Rsyncing folder: /local/vagrant/project/ => /vagrant

Where I have a subfolder in: /local/vagrant/project/server

I'd like to only rsync specific folders (./server), I've tried (and quite a few other syntax variations)

```
    config.vm.synced_folder "www/", "/vagrant/www", disabled: true
    config.vm.synced_folder "server/", "/vagrant/server"
```

Neither of these seem to make any difference (with debug info):

 INFO interface: info: Rsyncing folder: /local/vagrant/project/ => /vagrant
[solraws] Rsyncing folder:/local/vagrant/project/ => /vagrant
 INFO ssh: Execute: mkdir -p '/vagrant' (sudo=true)
 INFO ssh: Execute: chown ubuntu '/vagrant' (sudo=true)
 INFO subprocess: Starting process: ["rsync", "--verbose", "--archive", "-z", "--exclude", ".vagrant/", "-e", "ssh -p 22 -o StrictHostKeyChecking=no -i '/redacted'", "/local/vagrant/project/", "ubuntu@ec2-54-224-193-162.compute-1.amazonaws.com:/vagrant"]

I'm using a multi-vm vagrant file, where this is just one instance. Migrated the AWS vm to a single machine config, and this same code worked fine.

**Comment by tden012** [comment]
I know that this thread is old, but figured I should post here because I have the same problem.

I'm not using a multi-vm vagrant file, but the root is always rsynced, even if I want to rsync a different folder.

My problem is slightly different though... the root rsyncs, and so does folder that I specify in the vagrantfile. What I would like is for vagrant-aws to stop rsyncing the root by default. Is this possible?
