### ISSUE TITLE
Feature request: provide the ability to set the DeleteOnTermination flag for attached EBS volumes

### ISSUE THREAD

**Issue by jayjanssen** [mitchellh/vagrant-aws#119]
I'm leaking unattached EBS volumes all over the place here!  Would be perfect to configure my node to clean these up in my Vagrantfile

http://stackoverflow.com/questions/10923405/will-my-ebs-volume-in-my-ebs-backed-ec2-instance-persist

http://docs.aws.amazon.com/AWSEC2/latest/CommandLineReference/ApiReference-cmd-ModifyInstanceAttribute.html?r=4426

**Comment by utdrmac** [comment]
This possibly needs to be re-opened as the original issue is not resolved. Leaking root volumes still remain (even years later). If I create a new instance using an AMI, there's no way to specify that the root volume should be deleted. Doing the following actually creates a 2nd root device that you cannot access:

```
aws.block_device_mapping = [
{
	'DeviceName' => "xvda",
	'Ebs.VolumeSize' => 8,
	'Ebs.DeleteOnTermination' => true
}
```

Ideas on how to set it so that on termination of the instance the root volume goes away as well?

**Comment by poflynn** [comment]
Agree with @utdrmac - I too am having leaking unattached ebs volumes all over the place which is a real problem. I'm amazed more people aren't asking about this - is there a workaround or something I'm missing?

**Comment by jayjanssen** [comment]
DeleteOnTermination works just fine for non-root volumes AFAICT.

For root volumes, the AMI must properly have DeleteOnTermination set, this is outside of Vagrant's control.  In my case (and for @utdrmac), I found I could override this setting when my box is created in Packer:  https://github.com/jayjanssen/packer-percona/commit/d77738aa178700362d03d86bb1793fd4e0b8addd

**Comment by poflynn** [comment]
Nice tip, thanks!
