### ISSUE TITLE
Waiting for ssh to become available - but I restrict external access!

### ISSUE THREAD

**Issue by Hesse** [mitchellh/vagrant-aws#300]
Hi - 
I'm able to provision my instance without issue however it gets stuck on 'Waiting for SSH to become available...', the thing is I restrict external access. The only way you can access any of my VPC instances is to jump through a bastion server. The machine gets launched and I'm able to SSH in without issue (from the bastion). 

Is there a way I can disable this final check?

Thanks, 
H

**Comment by amosshapira** [comment]
@ColinHebert are you referring to config.ssh.proxy? That might help to make Vagrant use the bastion host but he still needs to somehow tell Vagrant to pass the private ip address instead of the public EIP.
In my digging (as part of https://groups.google.com/forum/#!topic/vagrant-up/8c4nO8KjPXg) I found that https://github.com/mitchellh/vagrant-aws/blob/master/lib/vagrant-aws/action/read_ssh_info.rb#L32 will use the EIP if assigned to the instance without a way to override.

**Comment by amosshapira** [comment]
I found an undocumented attribute - ssh_host_attribute, which is used in the code in https://github.com/mitchellh/vagrant-aws/blob/master/lib/vagrant-aws/action/read_ssh_info.rb#L32.

Adding the following solved an identical problem for us:
```ruby
config.vm.provider :aws do |aws, override|
  aws.ssh_host_attribute = [ :private_ip_address ]
end
```

The bug, as far as I can tell, is that it's not mentioned in README.md

**Comment by rtyler** [comment]
Closing this with the merge of #364
